import type { PublicProfileDetail, PublicProfileSummary } from '@nadar-kalyanam/schemas';

export const DUMMY_PROFILES: PublicProfileDetail[] = [
  {
    id: 'profile-priya-01',
    fullName: 'Priya Soundararajan',
    age: 26,
    gender: 'FEMALE',
    location: { city: 'Madurai', state: 'Tamil Nadu' },
    religion: 'Hindu',
    profession: 'Software Architect',
    maritalStatus: 'NEVER_MARRIED',
    primaryPhotoUrl:
      'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80',
    hasSentInterest: false,
    motherTongue: 'Tamil',
    height: '5 ft 4 in',
    physicalStatus: 'NORMAL',
    casteCommunity: 'Nadar',
    dosham: 'NO',
    education: {
      educationLevel: 'B.Tech',
      educationDetail: 'Computer Science & Engineering',
      profession: 'Software Architect',
      employedIn: 'Zoho Corporation',
      annualIncomeRange: '18 - 22 Lakhs',
      annualIncomeCurrency: 'INR',
    },
    additional: {
      familyType: 'Upper Middle Class',
      about:
        'I am an ambitious, warm-hearted software professional from Madurai. I enjoy traditional family gatherings, reading, and exploring south Indian cuisine. Seeking a supportive life partner from our community.',
    },
    photos: [
      {
        id: 'photo-priya-1',
        url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80',
        isPrimary: true,
        sortOrder: 0,
      },
      {
        id: 'photo-priya-2',
        url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=800&q=80',
        isPrimary: false,
        sortOrder: 1,
      },
    ],
  },
  {
    id: 'profile-karthik-02',
    fullName: 'Karthik Selvaraj',
    age: 28,
    gender: 'MALE',
    location: { city: 'Chennai', state: 'Tamil Nadu' },
    religion: 'Hindu',
    profession: 'Senior Product Manager',
    maritalStatus: 'NEVER_MARRIED',
    primaryPhotoUrl:
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80',
    hasSentInterest: false,
    motherTongue: 'Tamil',
    height: '5 ft 11 in',
    physicalStatus: 'NORMAL',
    casteCommunity: 'Nadar',
    dosham: 'NO',
    education: {
      educationLevel: 'Postgraduate',
      educationDetail: 'MBA (IIM Kozhikode) & B.E. EEE (CEG Anna University)',
      profession: 'Senior Product Manager',
      employedIn: 'Leading Fintech Enterprise',
      annualIncomeRange: '25 - 30 Lakhs',
      annualIncomeCurrency: 'INR',
    },
    additional: {
      familyType: 'Upper Middle Class',
      about:
        'Born and raised in Chennai with native roots in Sivakasi. Balanced mindset with modern career aspirations and strong family morals. Looking for an educated, understanding bride.',
    },
    photos: [
      {
        id: 'photo-karthik-1',
        url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80',
        isPrimary: true,
        sortOrder: 0,
      },
    ],
  },
  {
    id: 'profile-anitha-03',
    fullName: 'Dr. Anitha Murugesan',
    age: 27,
    gender: 'FEMALE',
    location: { city: 'Coimbatore', state: 'Tamil Nadu' },
    religion: 'Hindu',
    profession: 'Pediatric Specialist (MD)',
    maritalStatus: 'NEVER_MARRIED',
    primaryPhotoUrl:
      'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=800&q=80',
    hasSentInterest: false,
    motherTongue: 'Tamil',
    height: '5 ft 5 in',
    physicalStatus: 'NORMAL',
    casteCommunity: 'Nadar',
    dosham: 'NO',
    education: {
      educationLevel: 'Doctorate',
      educationDetail: 'MBBS, MD (Pediatrics) - PSG IMS&R',
      profession: 'Pediatric Specialist',
      employedIn: 'Kovai Medical Center & Hospital',
      annualIncomeRange: '20 - 25 Lakhs',
      annualIncomeCurrency: 'INR',
    },
    additional: {
      familyType: 'Rich / Affluent (Elite)',
      about:
        'Compassionate doctor practicing in Coimbatore. Passionate about children healthcare, classical music, and weekend badminton. Looking for a doctor or professional groom.',
    },
    photos: [
      {
        id: 'photo-anitha-1',
        url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=800&q=80',
        isPrimary: true,
        sortOrder: 0,
      },
    ],
  },
  {
    id: 'profile-vignesh-04',
    fullName: 'Er. Vignesh Pandian',
    age: 29,
    gender: 'MALE',
    location: { city: 'Tirunelveli', state: 'Tamil Nadu' },
    religion: 'Hindu',
    profession: 'Civil Contractor & Builder',
    maritalStatus: 'NEVER_MARRIED',
    primaryPhotoUrl:
      'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=800&q=80',
    hasSentInterest: false,
    motherTongue: 'Tamil',
    height: '5 ft 10 in',
    physicalStatus: 'NORMAL',
    casteCommunity: 'Nadar',
    dosham: 'DONT_KNOW',
    education: {
      educationLevel: 'B.E.',
      educationDetail: 'Civil Engineering (TCE Madurai)',
      profession: 'Managing Partner',
      employedIn: 'Pandian Infra & Developers',
      annualIncomeRange: '30 - 40 Lakhs',
      annualIncomeCurrency: 'INR',
    },
    additional: {
      familyType: 'Upper Middle Class',
      about:
        'Managing our family infrastructure business across South Tamil Nadu. Down to earth, energetic, and family-first. Looking for an affectionate partner with values.',
    },
    photos: [
      {
        id: 'photo-vignesh-1',
        url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=800&q=80',
        isPrimary: true,
        sortOrder: 0,
      },
    ],
  },
  {
    id: 'profile-divya-05',
    fullName: 'Divya Ramachandran, CA',
    age: 25,
    gender: 'FEMALE',
    location: { city: 'Tuticorin', state: 'Tamil Nadu' },
    religion: 'Hindu',
    profession: 'Chartered Accountant',
    maritalStatus: 'NEVER_MARRIED',
    primaryPhotoUrl:
      'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=800&q=80',
    hasSentInterest: false,
    motherTongue: 'Tamil',
    height: '5 ft 3 in',
    physicalStatus: 'NORMAL',
    casteCommunity: 'Nadar',
    dosham: 'NO',
    education: {
      educationLevel: 'Chartered Accountant',
      educationDetail: 'CA (ICAI) & B.Com (Loyola College)',
      profession: 'Senior Audit Associate',
      employedIn: 'Ernst & Young (EY)',
      annualIncomeRange: '14 - 18 Lakhs',
      annualIncomeCurrency: 'INR',
    },
    additional: {
      familyType: 'Middle Class',
      about:
        'Simple, cheerful, and hardworking CA working with Big 4 consulting. Enjoy traditional art, cooking festive treats, and family outings. Seeking an honest and caring groom.',
    },
    photos: [
      {
        id: 'photo-divya-1',
        url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=800&q=80',
        isPrimary: true,
        sortOrder: 0,
      },
    ],
  },
  {
    id: 'profile-saravanan-06',
    fullName: 'Saravanan Rajadurai',
    age: 30,
    gender: 'MALE',
    location: { city: 'Virudhunagar', state: 'Tamil Nadu' },
    religion: 'Hindu',
    profession: 'Export Business Director',
    maritalStatus: 'NEVER_MARRIED',
    primaryPhotoUrl:
      'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=800&q=80',
    hasSentInterest: false,
    motherTongue: 'Tamil',
    height: '5 ft 9 in',
    physicalStatus: 'NORMAL',
    casteCommunity: 'Nadar',
    dosham: 'NO',
    education: {
      educationLevel: 'Postgraduate',
      educationDetail: 'MBA (International Business) - PSG Tech',
      profession: 'Business Owner',
      employedIn: 'Rajadurai Spices & Oil Mills',
      annualIncomeRange: '40 - 50 Lakhs',
      annualIncomeCurrency: 'INR',
    },
    additional: {
      familyType: 'Rich / Affluent (Elite)',
      about:
        'Established family trading & export enterprise in Virudhunagar. Respectful of traditions while having modern outlook on life and marriage. Looking for an understanding bride.',
    },
    photos: [
      {
        id: 'photo-saravanan-1',
        url: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=800&q=80',
        isPrimary: true,
        sortOrder: 0,
      },
    ],
  },
  {
    id: 'profile-meenakshi-07',
    fullName: 'Meenakshi Sundaram',
    age: 24,
    gender: 'FEMALE',
    location: { city: 'Sivakasi', state: 'Tamil Nadu' },
    religion: 'Hindu',
    profession: 'Lead UI/UX Designer',
    maritalStatus: 'NEVER_MARRIED',
    primaryPhotoUrl:
      'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=800&q=80',
    hasSentInterest: false,
    motherTongue: 'Tamil',
    height: '5 ft 6 in',
    physicalStatus: 'NORMAL',
    casteCommunity: 'Nadar',
    dosham: 'NO',
    education: {
      educationLevel: 'B.Des',
      educationDetail: 'Design & Visual Communication',
      profession: 'Product Designer',
      employedIn: 'Freshworks Inc.',
      annualIncomeRange: '16 - 20 Lakhs',
      annualIncomeCurrency: 'INR',
    },
    additional: {
      familyType: 'Upper Middle Class',
      about:
        'Creative and outgoing designer living in Chennai with family in Sivakasi. Passionate about photography, heritage temples, and yoga. Seeking an open-minded companion.',
    },
    photos: [
      {
        id: 'photo-meenakshi-1',
        url: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=800&q=80',
        isPrimary: true,
        sortOrder: 0,
      },
    ],
  },
  {
    id: 'profile-arun-08',
    fullName: 'Arun Kumar Nadar',
    age: 31,
    gender: 'MALE',
    location: { city: 'Bangalore', state: 'Karnataka' },
    religion: 'Hindu',
    profession: 'Senior AI Engineer',
    maritalStatus: 'NEVER_MARRIED',
    primaryPhotoUrl:
      'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=800&q=80',
    hasSentInterest: false,
    motherTongue: 'Tamil',
    height: '6 ft 0 in',
    physicalStatus: 'NORMAL',
    casteCommunity: 'Nadar',
    dosham: 'NO',
    education: {
      educationLevel: 'Postgraduate',
      educationDetail: 'M.S. in Artificial Intelligence (NUS Singapore)',
      profession: 'Senior AI Research Engineer',
      employedIn: 'Microsoft Research India',
      annualIncomeRange: '35 - 45 Lakhs',
      annualIncomeCurrency: 'INR',
    },
    additional: {
      familyType: 'Upper Middle Class',
      about:
        'Tech enthusiast with a deep appreciation for classical Tamil traditions. Enjoy hiking, reading philosophy, and spending time with elders. Seeking a qualified and loving partner.',
    },
    photos: [
      {
        id: 'photo-arun-1',
        url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=800&q=80',
        isPrimary: true,
        sortOrder: 0,
      },
    ],
  },
  {
    id: 'profile-kavitha-09',
    fullName: 'Kavitha Thangavel',
    age: 28,
    gender: 'FEMALE',
    location: { city: 'Nagercoil', state: 'Tamil Nadu' },
    religion: 'Christian',
    profession: 'Assistant Professor',
    maritalStatus: 'NEVER_MARRIED',
    primaryPhotoUrl:
      'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=800&q=80',
    hasSentInterest: false,
    motherTongue: 'Tamil',
    height: '5 ft 4 in',
    physicalStatus: 'NORMAL',
    casteCommunity: 'Christian Nadar',
    dosham: 'NO',
    education: {
      educationLevel: 'Postgraduate',
      educationDetail: 'M.Sc., M.Phil (Mathematics) - Scott Christian College',
      profession: 'Assistant Professor',
      employedIn: 'Autonomous College of Arts & Science',
      annualIncomeRange: '10 - 12 Lakhs',
      annualIncomeCurrency: 'INR',
    },
    additional: {
      familyType: 'Middle Class',
      about:
        'Dedicated academic professional with calm temperament and Christian family values. Enjoys gardening, choir music, and teaching. Seeking a God-fearing, educated Nadar groom.',
    },
    photos: [
      {
        id: 'photo-kavitha-1',
        url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=800&q=80',
        isPrimary: true,
        sortOrder: 0,
      },
    ],
  },
  {
    id: 'profile-dinesh-10',
    fullName: 'Dinesh Raja',
    age: 28,
    gender: 'MALE',
    location: { city: 'Tiruchirappalli', state: 'Tamil Nadu' },
    religion: 'Hindu',
    profession: 'Branch Operations Manager',
    maritalStatus: 'NEVER_MARRIED',
    primaryPhotoUrl:
      'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=800&q=80',
    hasSentInterest: false,
    motherTongue: 'Tamil',
    height: '5 ft 10 in',
    physicalStatus: 'NORMAL',
    casteCommunity: 'Nadar',
    dosham: 'NO',
    education: {
      educationLevel: 'B.Com',
      educationDetail: 'B.Com & CAIIB (Certified Associate of Indian Institute of Bankers)',
      profession: 'Branch Manager',
      employedIn: 'State Bank of India',
      annualIncomeRange: '14 - 18 Lakhs',
      annualIncomeCurrency: 'INR',
    },
    additional: {
      familyType: 'Middle Class',
      about:
        'Banking officer with stable central government career. Sociable, respectful of family elders, and passionate about athletics and travel. Seeking a sweet-tempered companion.',
    },
    photos: [
      {
        id: 'photo-dinesh-1',
        url: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=800&q=80',
        isPrimary: true,
        sortOrder: 0,
      },
    ],
  },
];

export const DUMMY_SUMMARIES: PublicProfileSummary[] = DUMMY_PROFILES.map((p) => ({
  id: p.id,
  fullName: p.fullName,
  age: p.age,
  gender: p.gender,
  location: p.location,
  religion: p.religion,
  profession: p.profession,
  maritalStatus: p.maritalStatus,
  primaryPhotoUrl: p.primaryPhotoUrl,
  hasSentInterest: p.hasSentInterest,
}));
