import { computeCompletionScore } from '../common/profile-completion.js';
import type { PrismaClient } from '../generated/prisma/client.js';

// DEMO seed: 16 made-up members (stock photos, marked verified) for local
// development and demos only. Run explicitly with `pnpm prisma:seed:demo`;
// it is never part of the essential seed and refuses to run when
// NODE_ENV=production.
export const DEMO_SEED_PROFILES = [
  {
    phone: '+919876543201',
    fullName: 'Priya Soundararajan',
    gender: 'FEMALE',
    dateOfBirth: new Date('1998-05-14'),
    photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80',
    details: {
      motherTongue: 'Tamil',
      email: 'priya.soundar@example.com',
      height: '5 ft 4 in',
      physicalStatus: 'NORMAL',
      maritalStatus: 'NEVER_MARRIED',
      religion: 'Hindu',
      casteCommunity: 'Nadar',
      dosham: 'NO',
      location: { city: 'Madurai', state: 'Tamil Nadu', country: 'India' },
      education: {
        educationLevel: 'B.Tech',
        educationDetail: 'Computer Science & Engineering',
        profession: 'Software Architect',
        employedIn: 'Zoho Corporation',
        annualIncomeRange: '18 - 22 Lakhs',
        annualIncomeCurrency: 'INR',
      },
      additional: {
        familyType: 'Upper Middle Class',
        about: 'I am an ambitious, warm-hearted software professional from Madurai. I enjoy traditional family gatherings, reading, and exploring south Indian cuisine. Seeking a supportive life partner from our community.',
      },
    },
  },
  {
    phone: '+919876543202',
    fullName: 'Karthik Selvaraj',
    gender: 'MALE',
    dateOfBirth: new Date('1996-08-22'),
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80',
    details: {
      motherTongue: 'Tamil',
      email: 'karthik.selvaraj@example.com',
      height: '5 ft 11 in',
      physicalStatus: 'NORMAL',
      maritalStatus: 'NEVER_MARRIED',
      religion: 'Hindu',
      casteCommunity: 'Nadar',
      dosham: 'NO',
      location: { city: 'Chennai', state: 'Tamil Nadu', country: 'India' },
      education: {
        educationLevel: 'Postgraduate',
        educationDetail: 'MBA (IIM Kozhikode) & B.E. EEE',
        profession: 'Senior Product Manager',
        employedIn: 'Leading Fintech Enterprise',
        annualIncomeRange: '25 - 30 Lakhs',
        annualIncomeCurrency: 'INR',
      },
      additional: {
        familyType: 'Upper Middle Class',
        about: 'Born and raised in Chennai with native roots in Sivakasi. Balanced mindset with modern career aspirations and strong family morals. Looking for an educated, understanding bride.',
      },
    },
  },
  {
    phone: '+919876543203',
    fullName: 'Dr. Anitha Murugesan',
    gender: 'FEMALE',
    dateOfBirth: new Date('1997-11-03'),
    photoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=800&q=80',
    details: {
      motherTongue: 'Tamil',
      email: 'anitha.murugesan@example.com',
      height: '5 ft 5 in',
      physicalStatus: 'NORMAL',
      maritalStatus: 'NEVER_MARRIED',
      religion: 'Hindu',
      casteCommunity: 'Nadar',
      dosham: 'NO',
      location: { city: 'Coimbatore', state: 'Tamil Nadu', country: 'India' },
      education: {
        educationLevel: 'Doctorate',
        educationDetail: 'MBBS, MD (Pediatrics) - PSG IMS&R',
        profession: 'Pediatric Specialist',
        employedIn: 'Kovai Medical Center & Hospital',
        annualIncomeRange: '20 - 25 Lakhs',
        annualIncomeCurrency: 'INR',
      },
      additional: {
        familyType: 'Rich / Affluent (Elite)',
        about: 'Compassionate doctor practicing in Coimbatore. Passionate about children healthcare, classical music, and weekend badminton. Looking for a doctor or professional groom.',
      },
    },
  },
  {
    phone: '+919876543204',
    fullName: 'Er. Vignesh Pandian',
    gender: 'MALE',
    dateOfBirth: new Date('1995-03-18'),
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=800&q=80',
    details: {
      motherTongue: 'Tamil',
      email: 'vignesh.pandian@example.com',
      height: '5 ft 10 in',
      physicalStatus: 'NORMAL',
      maritalStatus: 'NEVER_MARRIED',
      religion: 'Hindu',
      casteCommunity: 'Nadar',
      dosham: 'DONT_KNOW',
      location: { city: 'Tirunelveli', state: 'Tamil Nadu', country: 'India' },
      education: {
        educationLevel: 'B.E.',
        educationDetail: 'Civil Engineering (TCE Madurai)',
        profession: 'Managing Partner',
        employedIn: 'Pandian Infra & Developers',
        annualIncomeRange: '30 - 40 Lakhs',
        annualIncomeCurrency: 'INR',
      },
      additional: {
        familyType: 'Upper Middle Class',
        about: 'Managing our family infrastructure business across South Tamil Nadu. Down to earth, energetic, and family-first. Looking for an affectionate partner with values.',
      },
    },
  },
  {
    phone: '+919876543205',
    fullName: 'Divya Ramachandran, CA',
    gender: 'FEMALE',
    dateOfBirth: new Date('1999-07-29'),
    photoUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=800&q=80',
    details: {
      motherTongue: 'Tamil',
      email: 'divya.ca@example.com',
      height: '5 ft 3 in',
      physicalStatus: 'NORMAL',
      maritalStatus: 'NEVER_MARRIED',
      religion: 'Hindu',
      casteCommunity: 'Nadar',
      dosham: 'NO',
      location: { city: 'Tuticorin', state: 'Tamil Nadu', country: 'India' },
      education: {
        educationLevel: 'Chartered Accountant',
        educationDetail: 'CA (ICAI) & B.Com (Loyola)',
        profession: 'Senior Audit Associate',
        employedIn: 'Ernst & Young (EY)',
        annualIncomeRange: '14 - 18 Lakhs',
        annualIncomeCurrency: 'INR',
      },
      additional: {
        familyType: 'Middle Class',
        about: 'Simple, cheerful, and hardworking CA working with Big 4 consulting. Enjoy traditional art, cooking festive treats, and family outings. Seeking an honest and caring groom.',
      },
    },
  },
  {
    phone: '+919876543206',
    fullName: 'Saravanan Rajadurai',
    gender: 'MALE',
    dateOfBirth: new Date('1994-12-10'),
    photoUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=800&q=80',
    details: {
      motherTongue: 'Tamil',
      email: 'saravanan.rajadurai@example.com',
      height: '5 ft 9 in',
      physicalStatus: 'NORMAL',
      maritalStatus: 'NEVER_MARRIED',
      religion: 'Hindu',
      casteCommunity: 'Nadar',
      dosham: 'NO',
      location: { city: 'Virudhunagar', state: 'Tamil Nadu', country: 'India' },
      education: {
        educationLevel: 'Postgraduate',
        educationDetail: 'MBA (International Business)',
        profession: 'Business Owner',
        employedIn: 'Rajadurai Spices & Oil Mills',
        annualIncomeRange: '40 - 50 Lakhs',
        annualIncomeCurrency: 'INR',
      },
      additional: {
        familyType: 'Rich / Affluent (Elite)',
        about: 'Established family trading & export enterprise in Virudhunagar. Respectful of traditions while having modern outlook on life and marriage. Looking for an understanding bride.',
      },
    },
  },
  {
    phone: '+919876543207',
    fullName: 'Meenakshi Sundaram',
    gender: 'FEMALE',
    dateOfBirth: new Date('2000-04-16'),
    photoUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=800&q=80',
    details: {
      motherTongue: 'Tamil',
      email: 'meenakshi.design@example.com',
      height: '5 ft 6 in',
      physicalStatus: 'NORMAL',
      maritalStatus: 'NEVER_MARRIED',
      religion: 'Hindu',
      casteCommunity: 'Nadar',
      dosham: 'NO',
      location: { city: 'Sivakasi', state: 'Tamil Nadu', country: 'India' },
      education: {
        educationLevel: 'B.Des',
        educationDetail: 'Design & Visual Communication',
        profession: 'Product Designer',
        employedIn: 'Freshworks Inc.',
        annualIncomeRange: '16 - 20 Lakhs',
        annualIncomeCurrency: 'INR',
      },
      additional: {
        familyType: 'Upper Middle Class',
        about: 'Creative and outgoing designer living in Chennai with family in Sivakasi. Passionate about photography, heritage temples, and yoga. Seeking an open-minded companion.',
      },
    },
  },
  {
    phone: '+919876543208',
    fullName: 'Arun Kumar Nadar',
    gender: 'MALE',
    dateOfBirth: new Date('1993-09-05'),
    photoUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=800&q=80',
    details: {
      motherTongue: 'Tamil',
      email: 'arun.kumar.ai@example.com',
      height: '6 ft 0 in',
      physicalStatus: 'NORMAL',
      maritalStatus: 'NEVER_MARRIED',
      religion: 'Hindu',
      casteCommunity: 'Nadar',
      dosham: 'NO',
      location: { city: 'Bangalore', state: 'Karnataka', country: 'India' },
      education: {
        educationLevel: 'Postgraduate',
        educationDetail: 'M.S. in Artificial Intelligence',
        profession: 'Senior AI Research Engineer',
        employedIn: 'Microsoft Research India',
        annualIncomeRange: '35 - 45 Lakhs',
        annualIncomeCurrency: 'INR',
      },
      additional: {
        familyType: 'Upper Middle Class',
        about: 'Tech enthusiast with a deep appreciation for classical Tamil traditions. Enjoy hiking, reading philosophy, and spending time with elders. Seeking a qualified and loving partner.',
      },
    },
  },
  {
    phone: '+919876543209',
    fullName: 'Kavitha Thangavel',
    gender: 'FEMALE',
    dateOfBirth: new Date('1996-01-21'),
    photoUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=800&q=80',
    details: {
      motherTongue: 'Tamil',
      email: 'kavitha.thangavel@example.com',
      height: '5 ft 4 in',
      physicalStatus: 'NORMAL',
      maritalStatus: 'NEVER_MARRIED',
      religion: 'Christian',
      casteCommunity: 'Christian Nadar',
      dosham: 'NO',
      location: { city: 'Nagercoil', state: 'Tamil Nadu', country: 'India' },
      education: {
        educationLevel: 'Postgraduate',
        educationDetail: 'M.Sc., M.Phil (Mathematics)',
        profession: 'Assistant Professor',
        employedIn: 'Autonomous Arts & Science College',
        annualIncomeRange: '10 - 12 Lakhs',
        annualIncomeCurrency: 'INR',
      },
      additional: {
        familyType: 'Middle Class',
        about: 'Dedicated academic professional with calm temperament and Christian family values. Enjoys gardening, choir music, and teaching. Seeking a God-fearing, educated Nadar groom.',
      },
    },
  },
  {
    phone: '+919876543210',
    fullName: 'Dinesh Raja',
    gender: 'MALE',
    dateOfBirth: new Date('1996-06-30'),
    photoUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=800&q=80',
    details: {
      motherTongue: 'Tamil',
      email: 'dinesh.raja.sbi@example.com',
      height: '5 ft 10 in',
      physicalStatus: 'NORMAL',
      maritalStatus: 'NEVER_MARRIED',
      religion: 'Hindu',
      casteCommunity: 'Nadar',
      dosham: 'NO',
      location: { city: 'Tiruchirappalli', state: 'Tamil Nadu', country: 'India' },
      education: {
        educationLevel: 'B.Com',
        educationDetail: 'B.Com & CAIIB',
        profession: 'Branch Manager',
        employedIn: 'State Bank of India',
        annualIncomeRange: '14 - 18 Lakhs',
        annualIncomeCurrency: 'INR',
      },
      additional: {
        familyType: 'Middle Class',
        about: 'Banking officer with stable central government career. Sociable, respectful of family elders, and passionate about athletics and travel. Seeking a sweet-tempered companion.',
      },
    },
  },
  {
    phone: '+919876543211',
    fullName: 'Deepa Soundarapandian',
    gender: 'FEMALE',
    dateOfBirth: new Date('1999-03-12'),
    photoUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=800&q=80',
    details: {
      motherTongue: 'Tamil',
      email: 'deepa.soundarapandian@example.com',
      height: '5 ft 5 in',
      physicalStatus: 'NORMAL',
      maritalStatus: 'NEVER_MARRIED',
      religion: 'Hindu',
      casteCommunity: 'Nadar',
      dosham: 'NO',
      location: { city: 'Chennai', state: 'Tamil Nadu', country: 'India' },
      education: {
        educationLevel: 'Postgraduate',
        educationDetail: 'M.S. in Data Science & B.Tech (Anna Univ)',
        profession: 'Lead Data Scientist',
        employedIn: 'Amazon Development Centre',
        annualIncomeRange: '22 - 28 Lakhs',
        annualIncomeCurrency: 'INR',
      },
      additional: {
        familyType: 'Upper Middle Class',
        about: 'Passionate data scientist who loves Carnatic vocal music and traveling with family. Value tradition, simplicity, and intellectual curiosity. Seeking a warm-hearted, educated partner.',
      },
    },
  },
  {
    phone: '+919876543212',
    fullName: 'Swathi Vasanthakumar',
    gender: 'FEMALE',
    dateOfBirth: new Date('2001-08-20'),
    photoUrl: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&w=800&q=80',
    details: {
      motherTongue: 'Tamil',
      email: 'swathi.vasanth@example.com',
      height: '5 ft 3 in',
      physicalStatus: 'NORMAL',
      maritalStatus: 'NEVER_MARRIED',
      religion: 'Hindu',
      casteCommunity: 'Nadar',
      dosham: 'NO',
      location: { city: 'Madurai', state: 'Tamil Nadu', country: 'India' },
      education: {
        educationLevel: 'B.Arch',
        educationDetail: 'B.Arch (SAP Anna University)',
        profession: 'Architectural Consultant',
        employedIn: 'Vasanth Design Associates',
        annualIncomeRange: '12 - 16 Lakhs',
        annualIncomeCurrency: 'INR',
      },
      additional: {
        familyType: 'Middle Class',
        about: 'Creative architect passionate about heritage preservation and sustainable interior design. Close to family and active in cultural festivals. Seeking an understanding life partner.',
      },
    },
  },
  {
    phone: '+919876543213',
    fullName: 'Lavanya Muthukrishnan',
    gender: 'FEMALE',
    dateOfBirth: new Date('1997-02-15'),
    photoUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=800&q=80',
    details: {
      motherTongue: 'Tamil',
      email: 'lavanya.muthu@example.com',
      height: '5 ft 6 in',
      physicalStatus: 'NORMAL',
      maritalStatus: 'NEVER_MARRIED',
      religion: 'Hindu',
      casteCommunity: 'Nadar',
      dosham: 'NO',
      location: { city: 'Tirunelveli', state: 'Tamil Nadu', country: 'India' },
      education: {
        educationLevel: 'Postgraduate',
        educationDetail: 'MBA (HR, LIBA Chennai)',
        profession: 'HR Business Partner',
        employedIn: 'Cognizant Technology Solutions',
        annualIncomeRange: '15 - 20 Lakhs',
        annualIncomeCurrency: 'INR',
      },
      additional: {
        familyType: 'Upper Middle Class',
        about: 'Empathetic and career-oriented HR professional from Tirunelveli. Enjoy home baking, badam halwa making, and reading literature. Looking for a respectful and caring life partner.',
      },
    },
  },
  {
    phone: '+919876543214',
    fullName: 'Dr. Manoj Kumar Ratnam',
    gender: 'MALE',
    dateOfBirth: new Date('1997-05-18'),
    photoUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=800&q=80',
    details: {
      motherTongue: 'Tamil',
      email: 'dr.manoj.ratnam@example.com',
      height: '5 ft 11 in',
      physicalStatus: 'NORMAL',
      maritalStatus: 'NEVER_MARRIED',
      religion: 'Hindu',
      casteCommunity: 'Nadar',
      dosham: 'NO',
      location: { city: 'Salem', state: 'Tamil Nadu', country: 'India' },
      education: {
        educationLevel: 'Doctorate',
        educationDetail: 'MBBS, MS (Orthopedics) - MMC Chennai',
        profession: 'Orthopedic Surgeon',
        employedIn: 'Manipal Hospitals',
        annualIncomeRange: '25 - 32 Lakhs',
        annualIncomeCurrency: 'INR',
      },
      additional: {
        familyType: 'Upper Middle Class',
        about: 'Dedicated orthopedic surgeon with strong ethical values. Passionate about sports medicine and community healthcare camps. Seeking an understanding and educated companion.',
      },
    },
  },
  {
    phone: '+919876543215',
    fullName: 'Kishore Rajasekar',
    gender: 'MALE',
    dateOfBirth: new Date('1999-11-04'),
    photoUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=800&q=80',
    details: {
      motherTongue: 'Tamil',
      email: 'kishore.rajasekar@example.com',
      height: '5 ft 10 in',
      physicalStatus: 'NORMAL',
      maritalStatus: 'NEVER_MARRIED',
      religion: 'Hindu',
      casteCommunity: 'Nadar',
      dosham: 'NO',
      location: { city: 'Coimbatore', state: 'Tamil Nadu', country: 'India' },
      education: {
        educationLevel: 'B.Tech',
        educationDetail: 'B.Tech (NIT Trichy)',
        profession: 'Fintech Product Lead',
        employedIn: 'Razorpay',
        annualIncomeRange: '28 - 35 Lakhs',
        annualIncomeCurrency: 'INR',
      },
      additional: {
        familyType: 'Middle Class',
        about: 'Tech professional working in fintech. Energetic, grounded in family values, and enthusiastic about south Indian history and cycling. Looking for an open-minded and loving bride.',
      },
    },
  },
  {
    phone: '+919876543216',
    fullName: 'Pradeep Chandran',
    gender: 'MALE',
    dateOfBirth: new Date('1998-09-25'),
    photoUrl: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?auto=format&fit=crop&w=800&q=80',
    details: {
      motherTongue: 'Tamil',
      email: 'pradeep.chandran@example.com',
      height: '6 ft 0 in',
      physicalStatus: 'NORMAL',
      maritalStatus: 'NEVER_MARRIED',
      religion: 'Hindu',
      casteCommunity: 'Nadar',
      dosham: 'NO',
      location: { city: 'Tuticorin', state: 'Tamil Nadu', country: 'India' },
      education: {
        educationLevel: 'B.E.',
        educationDetail: 'B.E. (Computer Science - PSG Tech)',
        profession: 'Cloud Solutions Architect',
        employedIn: 'Google Cloud India',
        annualIncomeRange: '32 - 40 Lakhs',
        annualIncomeCurrency: 'INR',
      },
      additional: {
        familyType: 'Upper Middle Class',
        about: 'Cloud architect based in Bangalore with native roots in Tuticorin. Deep family bonds, fond of coastal cuisine and photography. Seeking a well-educated partner with matching values.',
      },
    },
  },
];

export class DemoSeedRefusedError extends Error {}

export async function seedDemo(
  prisma: PrismaClient,
  nodeEnv: string | undefined,
  log: (message: string) => void = console.log,
): Promise<void> {
  if (nodeEnv === 'production') {
    throw new DemoSeedRefusedError('Refusing to seed demo members: NODE_ENV is production.');
  }
  for (const item of DEMO_SEED_PROFILES) {
    const user = await prisma.user.upsert({
      where: { phoneNumber: item.phone },
      update: { status: 'ACTIVE' },
      create: {
        phoneNumber: item.phone,
        status: 'ACTIVE',
      },
    });

    // Real score from the profile's fields, counting the photo seeded below.
    const completionScore = computeCompletionScore(
      { fullName: item.fullName, gender: item.gender, dateOfBirth: item.dateOfBirth, details: item.details },
      1,
    );
    const profile = await prisma.profile.upsert({
      where: { userId: user.id },
      update: {
        fullName: item.fullName,
        gender: item.gender,
        dateOfBirth: item.dateOfBirth,
        visibility: 'MEMBERS_ONLY',
        completionScore,
        isVerified: true,
        details: item.details,
      },
      create: {
        userId: user.id,
        fullName: item.fullName,
        gender: item.gender,
        dateOfBirth: item.dateOfBirth,
        visibility: 'MEMBERS_ONLY',
        completionScore,
        isVerified: true,
        details: item.details,
      },
    });

    // Seed primary photo
    const existingPhoto = await prisma.profilePhoto.findFirst({
      where: { profileId: profile.id },
    });

    if (!existingPhoto) {
      await prisma.profilePhoto.create({
        data: {
          profileId: profile.id,
          objectKey: item.photoUrl,
          isPrimary: true,
          sortOrder: 0,
          isModerated: true,
          isApproved: true,
        },
      });
    } else {
      await prisma.profilePhoto.update({
        where: { id: existingPhoto.id },
        data: {
          objectKey: item.photoUrl,
          isPrimary: true,
          isApproved: true,
          isModerated: true,
        },
      });
    }
  }

  log(`Seeded ${DEMO_SEED_PROFILES.length} demo member profiles (development only).`);
}
